#index:
#    path: /
#    controller: App\Controller\DefaultController::index

command::register-user:
  path: /api/commands/register-user
  defaults:
    _controller: App\Controller\CommandController:postAction
    command_class: App\User\Command\RegisterUser
