#index:
#    path: /
#    controller: App\Controller\DefaultController::index

command:user:register:
  path: /api/commands/user/register
  defaults:
    _controller: App\Controller\CommandController:postAction
    command_class: App\User\Command\RegisterUser

command:user:change-email:
  path: /api/commands/user/change-email
  defaults:
    _controller: App\Controller\CommandController:postAction
    command_class: App\User\Command\ChangeEmail

event::user-registered:
  path: /api/events/user-registered
  defaults:
    _controller: App\Controller\EventController:postAction
    event_class: App\User\Event\UserRegistered
